[package]
name = "trust-check"
version = "0.1.0"
authors = ["Alex Butler <alexheretic@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
curl = "0.4"
json = "0.12"

[profile.release]
lto = true
panic = "abort"
opt-level = "s"
strip = true
