[package]
name = "trust-check"
version = "0.0.0" # not published
authors = ["Alex Butler <alexheretic@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
ureq = { version = "2.10.1", features = ["json"] }

[profile.release]
lto = true
panic = "abort"
opt-level = "s"
strip = true
