#!/usr/bin/env bash
set -eu
script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

rm -rf "$script_dir"/*-999-*pkg*

cd "$script_dir"/..
tar zcf aurto-git.tar.gz --exclude='./target' --exclude='./trust-check/target' -C "$script_dir" .
mv aurto-git.tar.gz "$script_dir"/aur
cd "$script_dir"/aur

trap 'rm -f aurto-git.tar.gz && mv PKGBUILD.original PKGBUILD' EXIT
mv PKGBUILD PKGBUILD.original
current_v=$(grep '^pkgver=' PKGBUILD.original | cut -d'=' -f2 | tr -d '\n')
sed "s/###VERSION/$current_v/" ../makelocalaur.PKGBUILD > PKGBUILD

updpkgsums
makepkg "$@"

mv aurto-*-999* ../
