#!/usr/bin/env bash
## Aurto initialisation logic. 
## * ./install: Install aurto
## * ./install remove: Uninstall aurto
set -eu

command=${1:-}
user="${SUDO_USER:-$USER}"
lib_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# shellcheck source=./shared-functions disable=SC1091
source "$lib_dir/shared-functions"

# Initialise the aurto repo, trusted-users list & systemd timers
init() {
  echo "aurto: Initialising for user: $user"
  echo "$user" > /usr/lib/aurto/user
  chmod 700 /usr/lib/aurto/user

  install -d /var/cache/pacman/aurto -o "$user"
  sudo -u "$user" repo-add /var/cache/pacman/aurto/aurto.db.tar 2>/dev/null

  echo 'aurto: Adding include /etc/pacman.d/aurto >> pacman.conf' >&2
  if ! test -f /etc/pacman.conf.aurto-backup; then
    cp /etc/pacman.conf /etc/pacman.conf.aurto-backup
  fi
  echo -e "# aurto repo\\nInclude = /etc/pacman.d/aurto" >> /etc/pacman.conf

  if ! test -f /etc/aurto/trusted-users; then
    echo 'aurto: Adding default trusted users -> /etc/aurto/trusted-users' >&2
    install -Dm640 -o "$user" /usr/lib/aurto/default-trusted-users.txt /etc/aurto/trusted-users
  fi

  echo 'aurto: Adding & enabling systemd timer update tasks' >&2
  systemctl enable --now /usr/lib/systemd/system/check-aurto-git-trigger.timer
  systemctl enable --now /usr/lib/systemd/system/update-aurto.timer
  systemctl enable /usr/lib/systemd/system/update-aurto-startup.timer

  echo "aurto: Passwordless usage available for \`wheel\` group"
}

# Remove aurto repo files & disable systemd timers
pre_remove() {
  if ! initialised; then
    exit 0
  fi

  echo 'aurto: Removing systemd timer update tasks' >&2
  systemctl disable --now check-aurto-git-trigger.timer || true
  systemctl disable --now update-aurto.timer || true
  systemctl disable update-aurto-startup.timer || true

  echo 'aurto: Removing include from pacman.conf' >&2
  sed -i '/^Include = \/etc\/pacman.d\/aurto$/d' /etc/pacman.conf
  sed -i '/^# aurto repo$/d' /etc/pacman.conf

  echo 'aurto: Removing /var/cache/pacman/aurto' >&2
  rm -rf /var/cache/pacman/aurto 2>/dev/null || true

  rm -f /usr/lib/aurto/user 2>/dev/null || true
  rm -f /etc/aurto/trusted-users 2>/dev/null || true
  rm -d /etc/aurto 2>/dev/null || true
}

if [ -z "$command" ]; then
  if initialised; then
    echo 'aurto: already initialised ✓' >&2
    exit 0
  fi

  if [[ $EUID -ne 0 ]]; then 
    exec sudo "$0" "$@"
  fi

  init

elif [[ $command == "remove" ]]; then
  if [[ $EUID -ne 0 ]]; then 
    exec sudo "$0" "$@"
  fi
  pre_remove

else
  echo "unknown command: $command" >&2
  exit 1
fi