#!/usr/bin/env bash
if test -t 1; then
  function bold { echo -e "\\e[1m$*\\e[0m"; }
  function green { echo -e "\\e[32m$*\\e[39m"; }
  function cyan { echo -e "\\e[36m$*\\e[39m"; }
  function red { echo -e "\\e[31m$*\\e[39m"; }
  function dim { echo -e "\\e[2m$*\\e[22m"; }
  function rm_last_print {
    printf "\\033[1A"  # move cursor one line up
    printf "\\033[K"  # delete till end of line
  }
else
  function bold { echo -e "$*"; }
  function green { bold "$@"; }
  function cyan { bold "$@"; }
  function red { bold "$@"; }
  function dim { bold "$@"; }
  function rm_last_print { return; }
fi

function last_pkg_modify {
  stat /var/cache/pacman/aurto/*.pkg.tar* -c '%Y' 2>/dev/null | sort | tail -n1 | tr -d '\n'
}
