#!/usr/bin/env bash
## Summerizes steps to shorten aurutils/makepkg build output
## prints full output if command fails
set -eu

lib_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# shellcheck source=./shared-functions disable=SC1091
source "$lib_dir/shared-functions"

activity=""
subactivity=""
last_echo=""
full_output_file=$(mktemp /tmp/aurto.XXXXXX)
trap 'rm -f $full_output_file' EXIT

# ensure a line has been printed
echo

"${@:1}" 2>&1 | tee "$full_output_file" |
  while IFS= read -r line; do
    if [[ $line = "==> "* ]]; then
      activity="${line:4}"
      subactivity=""
    elif [[ $line = "  -> "* ]]; then
      subactivity="${line:5}"
    elif [[ $line = *"there is nothing to do" ]]; then
      subactivity="there is nothing to do"
    fi

    if [[ $last_echo != " $activity $subactivity" ]]; then
      last_echo=" $activity $subactivity"
      rm_last_print
      echo "$last_echo"
    fi
  done

if [[ ${PIPESTATUS[0]} -ne 0 ]]; then
  cat "$full_output_file" >&2
  echo "\`${*:1}\` failed with exit code ${PIPESTATUS[0]} $(red ✗)" >&2
  exit "${PIPESTATUS[0]}"
fi
