#!/usr/bin/env bash
## Builds new aur packages into repo 'aurto' (run as root)
## Should be in the same dir as `check-aurto-git`
set -eu

lib_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
user=$(cat /usr/lib/aurto/user)
# shellcheck source=./shared-functions disable=SC1091
source "$lib_dir/shared-functions"

if [ -z "$user" ]; then
  echo 'Missing /usr/lib/aurto/user' >&2
  exit 1
fi

pacsync aurto >/dev/null || true

modify=$(last_pkg_modify)

echo "Running: aursync --no-view --no-confirm --repo aurto --chroot --update" >&2
sudo -u "$user" \
 "$lib_dir"/summerize-build \
 aursync --no-view --no-confirm --repo aurto --chroot --update

if rm "$lib_dir/check-vcs" 2>/dev/null; then
  git_outdated=$("$lib_dir/check-aurto-git")
  if [ -n "$git_outdated" ]; then
    sudo -u "$user" aurto add "$git_outdated"
  fi
fi

pacsync aurto || true
paccache -rk1 -c /var/cache/pacman/aurto

after_modify=$(last_pkg_modify)
if [ "${after_modify:-0}" != "${modify:-0}" ]; then
  ## prompt listeners to `/var/lib/pacman/local` that something has changed
  ## E.g. RaphaelRochet/arch-update
  touch /var/lib/pacman/local/aurto-arch-update
fi
