#!/usr/bin/env bash
## Builds new aur packages into repo 'aurto' (run as root)
## Should be in the same dir as `check-aurto-git`
set -eu

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
user=$(cat /usr/lib/aurto/user)

if [ -z "$user" ]; then
  echo 'Missing /usr/lib/aurto/user' >&2
  exit 1
fi

pacsync aurto

sudo -u "$user" aursync --no-view --rmdeps --no-confirm --repo aurto --chroot --update

if rm "$script_dir/check-vcs" 2>/dev/null; then
  git_outdated=$("$script_dir/check-aurto-git")
  if [ -n "$git_outdated" ]; then
    sudo -u "$user" aurto add "$git_outdated"
  fi
fi

pacsync aurto
paccache -rk1 -c /var/cache/pacman/aurto
