#!/usr/bin/env bash
## Builds new aur packages into repo 'aurto'
## Should be in the same dir as `check-aurto-git`
set -eu

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
user=$(cat /usr/lib/aurto/user)

if [ -z "$user" ]; then
  echo 'Missing /usr/lib/aurto/user' >&2
  exit 1
fi

pacsync aurto

sudo -u "$user" aursync --no-view --rmdeps --no-confirm --repo aurto --chroot --update

if rm /usr/lib/aurto/check-vcs 2>/dev/null; then
  GIT_OUTDATED=$("$SCRIPT_DIR"/check-aurto-git)
  if [ -n "$GIT_OUTDATED" ]; then
    sudo -u "$user" aurto add "$GIT_OUTDATED"
  fi
fi

pacsync aurto
paccache -rk1 -c /var/cache/pacman/aurto
