name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: rustup update stable
    - run: wget -c https://github.com/koalaman/shellcheck/releases/download/latest/shellcheck-latest.linux.x86_64.tar.xz -O - | tar -xvJ -C /tmp/
    - uses: actions/checkout@v4
    - name: ./test
      run: PATH="/tmp/shellcheck-latest:$PATH" ./test
